# Generated by Django 5.0.4 on 2024-07-11 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DaCrm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='phone_number',
            field=models.CharField(default='', max_length=15),
        ),
    ]
